[package]
name = "lever"
version = "0.1.0"
authors = ["Luc Perkins <lucperkins@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "1.0.1"
chrono = "0.4.19"
uuid = { version = "0.8.2", features = ["v4"] }